USE cyberwikia_test;
INSERT INTO country (name, code, icon_file) VALUES ('Afghanistan', 'AF', 'images/flags/af.png');
INSERT INTO country (name, code, icon_file) VALUES ('Aland Islands', 'AX', 'images/flags/ax.png');
INSERT INTO country (name, code, icon_file) VALUES ('Albania', 'AL', 'images/flags/al.png');
INSERT INTO country (name, code, icon_file) VALUES ('Algeria', 'DZ', 'images/flags/dz.png');
INSERT INTO country (name, code, icon_file) VALUES ('American Samoa', 'AS', 'images/flags/as.png');
INSERT INTO country (name, code, icon_file) VALUES ('Andorra', 'AD', 'images/flags/ad.png');
INSERT INTO country (name, code, icon_file) VALUES ('Angola', 'AO', 'images/flags/ao.png');
INSERT INTO country (name, code, icon_file) VALUES ('Anguilla', 'AI', 'images/flags/ai.png');
INSERT INTO country (name, code, icon_file) VALUES ('Antarctica', 'AQ', 'images/flags/aq.png');
INSERT INTO country (name, code, icon_file) VALUES ('Antigua and Barbuda', 'AG', 'images/flags/ag.png');
INSERT INTO country (name, code, icon_file) VALUES ('Argentina', 'AR', 'images/flags/ar.png');
INSERT INTO country (name, code, icon_file) VALUES ('Armenia', 'AM', 'images/flags/am.png');
INSERT INTO country (name, code, icon_file) VALUES ('Aruba', 'AW', 'images/flags/aw.png');
INSERT INTO country (name, code, icon_file) VALUES ('Australia', 'AU', 'images/flags/au.png');
INSERT INTO country (name, code, icon_file) VALUES ('Austria', 'AT', 'images/flags/at.png');
INSERT INTO country (name, code, icon_file) VALUES ('Azerbaijan', 'AZ', 'images/flags/az.png');
INSERT INTO country (name, code, icon_file) VALUES ('Bahamas', 'BS', 'images/flags/bs.png');
INSERT INTO country (name, code, icon_file) VALUES ('Bahrain', 'BH', 'images/flags/bh.png');
INSERT INTO country (name, code, icon_file) VALUES ('Bangladesh', 'BD', 'images/flags/bd.png');
INSERT INTO country (name, code, icon_file) VALUES ('Barbados', 'BB', 'images/flags/bb.png');
INSERT INTO country (name, code, icon_file) VALUES ('Belarus', 'BY', 'images/flags/by.png');
INSERT INTO country (name, code, icon_file) VALUES ('Belgium', 'BE', 'images/flags/be.png');
INSERT INTO country (name, code, icon_file) VALUES ('Belize', 'BZ', 'images/flags/bz.png');
INSERT INTO country (name, code, icon_file) VALUES ('Benin', 'BJ', 'images/flags/bj.png');
INSERT INTO country (name, code, icon_file) VALUES ('Bermuda', 'BM', 'images/flags/bm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Bhutan', 'BT', 'images/flags/bt.png');
INSERT INTO country (name, code, icon_file) VALUES ('Bolivia, Plurinational State of', 'BO', 'images/flags/bo.png');
INSERT INTO country (name, code, icon_file) VALUES ('Bonaire, Sint Eustatius and Saba', 'BQ', 'images/flags/bq.png');
INSERT INTO country (name, code, icon_file) VALUES ('Bosnia and Herzegovina', 'BA', 'images/flags/ba.png');
INSERT INTO country (name, code, icon_file) VALUES ('Botswana', 'BW', 'images/flags/bw.png');
INSERT INTO country (name, code, icon_file) VALUES ('Bouvet Island', 'BV', 'images/flags/bv.png');
INSERT INTO country (name, code, icon_file) VALUES ('Brazil', 'BR', 'images/flags/br.png');
INSERT INTO country (name, code, icon_file) VALUES ('British Indian Ocean Territory', 'IO', 'images/flags/io.png');
INSERT INTO country (name, code, icon_file) VALUES ('Brunei Darussalam', 'BN', 'images/flags/bn.png');
INSERT INTO country (name, code, icon_file) VALUES ('Bulgaria', 'BG', 'images/flags/bg.png');
INSERT INTO country (name, code, icon_file) VALUES ('Burkina Faso', 'BF', 'images/flags/bf.png');
INSERT INTO country (name, code, icon_file) VALUES ('Burundi', 'BI', 'images/flags/bi.png');
INSERT INTO country (name, code, icon_file) VALUES ('Cambodia', 'KH', 'images/flags/kh.png');
INSERT INTO country (name, code, icon_file) VALUES ('Cameroon', 'CM', 'images/flags/cm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Canada', 'CA', 'images/flags/ca.png');
INSERT INTO country (name, code, icon_file) VALUES ('Cape Verde', 'CV', 'images/flags/cv.png');
INSERT INTO country (name, code, icon_file) VALUES ('Cayman Islands', 'KY', 'images/flags/ky.png');
INSERT INTO country (name, code, icon_file) VALUES ('Central African Republic', 'CF', 'images/flags/cf.png');
INSERT INTO country (name, code, icon_file) VALUES ('Chad', 'TD', 'images/flags/td.png');
INSERT INTO country (name, code, icon_file) VALUES ('Chile', 'CL', 'images/flags/cl.png');
INSERT INTO country (name, code, icon_file) VALUES ('China', 'CN', 'images/flags/cn.png');
INSERT INTO country (name, code, icon_file) VALUES ('Christmas Island', 'CX', 'images/flags/cx.png');
INSERT INTO country (name, code, icon_file) VALUES ('Cocos (Keeling) Islands', 'CC', 'images/flags/cc.png');
INSERT INTO country (name, code, icon_file) VALUES ('Colombia', 'CO', 'images/flags/co.png');
INSERT INTO country (name, code, icon_file) VALUES ('Comoros', 'KM', 'images/flags/km.png');
INSERT INTO country (name, code, icon_file) VALUES ('Congo', 'CG', 'images/flags/cg.png');
INSERT INTO country (name, code, icon_file) VALUES ('Congo, the Democratic Republic of the', 'CD', 'images/flags/cd.png');
INSERT INTO country (name, code, icon_file) VALUES ('Cook Islands', 'CK', 'images/flags/ck.png');
INSERT INTO country (name, code, icon_file) VALUES ('Costa Rica', 'CR', 'images/flags/cr.png');
INSERT INTO country (name, code, icon_file) VALUES ('Cote d''Ivoire', 'CI', 'images/flags/ci.png');
INSERT INTO country (name, code, icon_file) VALUES ('Croatia', 'HR', 'images/flags/hr.png');
INSERT INTO country (name, code, icon_file) VALUES ('Cuba', 'CU', 'images/flags/cu.png');
INSERT INTO country (name, code, icon_file) VALUES ('Curacao', 'CW', 'images/flags/cw.png');
INSERT INTO country (name, code, icon_file) VALUES ('Cyprus', 'CY', 'images/flags/cy.png');
INSERT INTO country (name, code, icon_file) VALUES ('Czech Republic', 'CZ', 'images/flags/cz.png');
INSERT INTO country (name, code, icon_file) VALUES ('Denmark', 'DK', 'images/flags/dk.png');
INSERT INTO country (name, code, icon_file) VALUES ('Djibouti', 'DJ', 'images/flags/dj.png');
INSERT INTO country (name, code, icon_file) VALUES ('Dominica', 'DM', 'images/flags/dm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Dominican Republic', 'DO', 'images/flags/do.png');
INSERT INTO country (name, code, icon_file) VALUES ('Ecuador', 'EC', 'images/flags/ec.png');
INSERT INTO country (name, code, icon_file) VALUES ('Egypt', 'EG', 'images/flags/eg.png');
INSERT INTO country (name, code, icon_file) VALUES ('El Salvador', 'SV', 'images/flags/sv.png');
INSERT INTO country (name, code, icon_file) VALUES ('Equatorial Guinea', 'GQ', 'images/flags/gq.png');
INSERT INTO country (name, code, icon_file) VALUES ('Eritrea', 'ER', 'images/flags/er.png');
INSERT INTO country (name, code, icon_file) VALUES ('Estonia', 'EE', 'images/flags/ee.png');
INSERT INTO country (name, code, icon_file) VALUES ('Ethiopia', 'ET', 'images/flags/et.png');
INSERT INTO country (name, code, icon_file) VALUES ('Falkland Islands (Malvinas)', 'FK', 'images/flags/fk.png');
INSERT INTO country (name, code, icon_file) VALUES ('Faroe Islands', 'FO', 'images/flags/fo.png');
INSERT INTO country (name, code, icon_file) VALUES ('Fiji', 'FJ', 'images/flags/fj.png');
INSERT INTO country (name, code, icon_file) VALUES ('Finland', 'FI', 'images/flags/fi.png');
INSERT INTO country (name, code, icon_file) VALUES ('France', 'FR', 'images/flags/fr.png');
INSERT INTO country (name, code, icon_file) VALUES ('French Guiana', 'GF', 'images/flags/gf.png');
INSERT INTO country (name, code, icon_file) VALUES ('French Polynesia', 'PF', 'images/flags/pf.png');
INSERT INTO country (name, code, icon_file) VALUES ('French Southern Territories', 'TF', 'images/flags/tf.png');
INSERT INTO country (name, code, icon_file) VALUES ('Gabon', 'GA', 'images/flags/ga.png');
INSERT INTO country (name, code, icon_file) VALUES ('Gambia', 'GM', 'images/flags/gm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Georgia', 'GE', 'images/flags/ge.png');
INSERT INTO country (name, code, icon_file) VALUES ('Germany', 'DE', 'images/flags/de.png');
INSERT INTO country (name, code, icon_file) VALUES ('Ghana', 'GH', 'images/flags/gh.png');
INSERT INTO country (name, code, icon_file) VALUES ('Gibraltar', 'GI', 'images/flags/gi.png');
INSERT INTO country (name, code, icon_file) VALUES ('Greece', 'GR', 'images/flags/gr.png');
INSERT INTO country (name, code, icon_file) VALUES ('Greenland', 'GL', 'images/flags/gl.png');
INSERT INTO country (name, code, icon_file) VALUES ('Grenada', 'GD', 'images/flags/gd.png');
INSERT INTO country (name, code, icon_file) VALUES ('Guadeloupe', 'GP', 'images/flags/gp.png');
INSERT INTO country (name, code, icon_file) VALUES ('Guam', 'GU', 'images/flags/gu.png');
INSERT INTO country (name, code, icon_file) VALUES ('Guatemala', 'GT', 'images/flags/gt.png');
INSERT INTO country (name, code, icon_file) VALUES ('Guernsey', 'GG', 'images/flags/gg.png');
INSERT INTO country (name, code, icon_file) VALUES ('Guinea', 'GN', 'images/flags/gn.png');
INSERT INTO country (name, code, icon_file) VALUES ('Guinea-Bissau', 'GW', 'images/flags/gw.png');
INSERT INTO country (name, code, icon_file) VALUES ('Guyana', 'GY', 'images/flags/gy.png');
INSERT INTO country (name, code, icon_file) VALUES ('Haiti', 'HT', 'images/flags/ht.png');
INSERT INTO country (name, code, icon_file) VALUES ('Heard Island and McDonald Islands', 'HM', 'images/flags/hm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Holy See (Vatican City State)', 'VA', 'images/flags/va.png');
INSERT INTO country (name, code, icon_file) VALUES ('Honduras', 'HN', 'images/flags/hn.png');
INSERT INTO country (name, code, icon_file) VALUES ('Hong Kong', 'HK', 'images/flags/hk.png');
INSERT INTO country (name, code, icon_file) VALUES ('Hungary', 'HU', 'images/flags/hu.png');
INSERT INTO country (name, code, icon_file) VALUES ('Iceland', 'IS', 'images/flags/is.png');
INSERT INTO country (name, code, icon_file) VALUES ('India', 'IN', 'images/flags/in.png');
INSERT INTO country (name, code, icon_file) VALUES ('Indonesia', 'ID', 'images/flags/id.png');
INSERT INTO country (name, code, icon_file) VALUES ('Iran, Islamic Republic of', 'IR', 'images/flags/ir.png');
INSERT INTO country (name, code, icon_file) VALUES ('Iraq', 'IQ', 'images/flags/iq.png');
INSERT INTO country (name, code, icon_file) VALUES ('Ireland', 'IE', 'images/flags/ie.png');
INSERT INTO country (name, code, icon_file) VALUES ('Isle of Man', 'IM', 'images/flags/im.png');
INSERT INTO country (name, code, icon_file) VALUES ('Israel', 'IL', 'images/flags/il.png');
INSERT INTO country (name, code, icon_file) VALUES ('Italy', 'IT', 'images/flags/it.png');
INSERT INTO country (name, code, icon_file) VALUES ('Jamaica', 'JM', 'images/flags/jm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Japan', 'JP', 'images/flags/jp.png');
INSERT INTO country (name, code, icon_file) VALUES ('Jersey', 'JE', 'images/flags/je.png');
INSERT INTO country (name, code, icon_file) VALUES ('Jordan', 'JO', 'images/flags/jo.png');
INSERT INTO country (name, code, icon_file) VALUES ('Kazakhstan', 'KZ', 'images/flags/kz.png');
INSERT INTO country (name, code, icon_file) VALUES ('Kenya', 'KE', 'images/flags/ke.png');
INSERT INTO country (name, code, icon_file) VALUES ('Kiribati', 'KI', 'images/flags/ki.png');
INSERT INTO country (name, code, icon_file) VALUES ('Korea, Democratic People''s Republic of', 'KP', 'images/flags/kp.png');
INSERT INTO country (name, code, icon_file) VALUES ('Korea, Republic of', 'KR', 'images/flags/kr.png');
INSERT INTO country (name, code, icon_file) VALUES ('Kuwait', 'KW', 'images/flags/kw.png');
INSERT INTO country (name, code, icon_file) VALUES ('Kyrgyzstan', 'KG', 'images/flags/kg.png');
INSERT INTO country (name, code, icon_file) VALUES ('Lao People''s Democratic Republic', 'LA', 'images/flags/la.png');
INSERT INTO country (name, code, icon_file) VALUES ('Latvia', 'LV', 'images/flags/lv.png');
INSERT INTO country (name, code, icon_file) VALUES ('Lebanon', 'LB', 'images/flags/lb.png');
INSERT INTO country (name, code, icon_file) VALUES ('Lesotho', 'LS', 'images/flags/ls.png');
INSERT INTO country (name, code, icon_file) VALUES ('Liberia', 'LR', 'images/flags/lr.png');
INSERT INTO country (name, code, icon_file) VALUES ('Libya', 'LY', 'images/flags/ly.png');
INSERT INTO country (name, code, icon_file) VALUES ('Liechtenstein', 'LI', 'images/flags/li.png');
INSERT INTO country (name, code, icon_file) VALUES ('Lithuania', 'LT', 'images/flags/lt.png');
INSERT INTO country (name, code, icon_file) VALUES ('Luxembourg', 'LU', 'images/flags/lu.png');
INSERT INTO country (name, code, icon_file) VALUES ('Macao', 'MO', 'images/flags/mo.png');
INSERT INTO country (name, code, icon_file) VALUES ('Macedonia, the Former Yugoslav Republic of', 'MK', 'images/flags/mk.png');
INSERT INTO country (name, code, icon_file) VALUES ('Madagascar', 'MG', 'images/flags/mg.png');
INSERT INTO country (name, code, icon_file) VALUES ('Malawi', 'MW', 'images/flags/mw.png');
INSERT INTO country (name, code, icon_file) VALUES ('Malaysia', 'MY', 'images/flags/my.png');
INSERT INTO country (name, code, icon_file) VALUES ('Maldives', 'MV', 'images/flags/mv.png');
INSERT INTO country (name, code, icon_file) VALUES ('Mali', 'ML', 'images/flags/ml.png');
INSERT INTO country (name, code, icon_file) VALUES ('Malta', 'MT', 'images/flags/mt.png');
INSERT INTO country (name, code, icon_file) VALUES ('Marshall Islands', 'MH', 'images/flags/mh.png');
INSERT INTO country (name, code, icon_file) VALUES ('Martinique', 'MQ', 'images/flags/mq.png');
INSERT INTO country (name, code, icon_file) VALUES ('Mauritania', 'MR', 'images/flags/mr.png');
INSERT INTO country (name, code, icon_file) VALUES ('Mauritius', 'MU', 'images/flags/mu.png');
INSERT INTO country (name, code, icon_file) VALUES ('Mayotte', 'YT', 'images/flags/yt.png');
INSERT INTO country (name, code, icon_file) VALUES ('Mexico', 'MX', 'images/flags/mx.png');
INSERT INTO country (name, code, icon_file) VALUES ('Micronesia, Federated States of', 'FM', 'images/flags/fm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Moldova, Republic of', 'MD', 'images/flags/md.png');
INSERT INTO country (name, code, icon_file) VALUES ('Monaco', 'MC', 'images/flags/mc.png');
INSERT INTO country (name, code, icon_file) VALUES ('Mongolia', 'MN', 'images/flags/mn.png');
INSERT INTO country (name, code, icon_file) VALUES ('Montenegro', 'ME', 'images/flags/me.png');
INSERT INTO country (name, code, icon_file) VALUES ('Montserrat', 'MS', 'images/flags/ms.png');
INSERT INTO country (name, code, icon_file) VALUES ('Morocco', 'MA', 'images/flags/ma.png');
INSERT INTO country (name, code, icon_file) VALUES ('Mozambique', 'MZ', 'images/flags/mz.png');
INSERT INTO country (name, code, icon_file) VALUES ('Myanmar', 'MM', 'images/flags/mm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Namibia', 'NA', 'images/flags/na.png');
INSERT INTO country (name, code, icon_file) VALUES ('Nauru', 'NR', 'images/flags/nr.png');
INSERT INTO country (name, code, icon_file) VALUES ('Nepal', 'NP', 'images/flags/np.png');
INSERT INTO country (name, code, icon_file) VALUES ('Netherlands', 'NL', 'images/flags/nl.png');
INSERT INTO country (name, code, icon_file) VALUES ('New Caledonia', 'NC', 'images/flags/nc.png');
INSERT INTO country (name, code, icon_file) VALUES ('New Zealand', 'NZ', 'images/flags/nz.png');
INSERT INTO country (name, code, icon_file) VALUES ('Nicaragua', 'NI', 'images/flags/ni.png');
INSERT INTO country (name, code, icon_file) VALUES ('Niger', 'NE', 'images/flags/ne.png');
INSERT INTO country (name, code, icon_file) VALUES ('Nigeria', 'NG', 'images/flags/ng.png');
INSERT INTO country (name, code, icon_file) VALUES ('Niue', 'NU', 'images/flags/nu.png');
INSERT INTO country (name, code, icon_file) VALUES ('Norfolk Island', 'NF', 'images/flags/nf.png');
INSERT INTO country (name, code, icon_file) VALUES ('Northern Mariana Islands', 'MP', 'images/flags/mp.png');
INSERT INTO country (name, code, icon_file) VALUES ('Norway', 'NO', 'images/flags/no.png');
INSERT INTO country (name, code, icon_file) VALUES ('Oman', 'OM', 'images/flags/om.png');
INSERT INTO country (name, code, icon_file) VALUES ('Pakistan', 'PK', 'images/flags/pk.png');
INSERT INTO country (name, code, icon_file) VALUES ('Palau', 'PW', 'images/flags/pw.png');
INSERT INTO country (name, code, icon_file) VALUES ('Palestine, State of', 'PS', 'images/flags/ps.png');
INSERT INTO country (name, code, icon_file) VALUES ('Panama', 'PA', 'images/flags/pa.png');
INSERT INTO country (name, code, icon_file) VALUES ('Papua New Guinea', 'PG', 'images/flags/pg.png');
INSERT INTO country (name, code, icon_file) VALUES ('Paraguay', 'PY', 'images/flags/py.png');
INSERT INTO country (name, code, icon_file) VALUES ('Peru', 'PE', 'images/flags/pe.png');
INSERT INTO country (name, code, icon_file) VALUES ('Philippines', 'PH', 'images/flags/ph.png');
INSERT INTO country (name, code, icon_file) VALUES ('Pitcairn', 'PN', 'images/flags/pn.png');
INSERT INTO country (name, code, icon_file) VALUES ('Poland', 'PL', 'images/flags/pl.png');
INSERT INTO country (name, code, icon_file) VALUES ('Portugal', 'PT', 'images/flags/pt.png');
INSERT INTO country (name, code, icon_file) VALUES ('Puerto Rico', 'PR', 'images/flags/pr.png');
INSERT INTO country (name, code, icon_file) VALUES ('Qatar', 'QA', 'images/flags/qa.png');
INSERT INTO country (name, code, icon_file) VALUES ('Reunion', 'RE', 'images/flags/re.png');
INSERT INTO country (name, code, icon_file) VALUES ('Romania', 'RO', 'images/flags/ro.png');
INSERT INTO country (name, code, icon_file) VALUES ('Russian Federation', 'RU', 'images/flags/ru.png');
INSERT INTO country (name, code, icon_file) VALUES ('Rwanda', 'RW', 'images/flags/rw.png');
INSERT INTO country (name, code, icon_file) VALUES ('Saint Barthelemy', 'BL', 'images/flags/bl.png');
INSERT INTO country (name, code, icon_file) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'images/flags/sh.png');
INSERT INTO country (name, code, icon_file) VALUES ('Saint Kitts and Nevis', 'KN', 'images/flags/kn.png');
INSERT INTO country (name, code, icon_file) VALUES ('Saint Lucia', 'LC', 'images/flags/lc.png');
INSERT INTO country (name, code, icon_file) VALUES ('Saint Martin (French part)', 'MF', 'images/flags/mf.png');
INSERT INTO country (name, code, icon_file) VALUES ('Saint Pierre and Miquelon', 'PM', 'images/flags/pm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Saint Vincent and the Grenadines', 'VC', 'images/flags/vc.png');
INSERT INTO country (name, code, icon_file) VALUES ('Samoa', 'WS', 'images/flags/ws.png');
INSERT INTO country (name, code, icon_file) VALUES ('San Marino', 'SM', 'images/flags/sm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Sao Tome and Principe', 'ST', 'images/flags/st.png');
INSERT INTO country (name, code, icon_file) VALUES ('Saudi Arabia', 'SA', 'images/flags/sa.png');
INSERT INTO country (name, code, icon_file) VALUES ('Senegal', 'SN', 'images/flags/sn.png');
INSERT INTO country (name, code, icon_file) VALUES ('Serbia', 'RS', 'images/flags/rs.png');
INSERT INTO country (name, code, icon_file) VALUES ('Seychelles', 'SC', 'images/flags/sc.png');
INSERT INTO country (name, code, icon_file) VALUES ('Sierra Leone', 'SL', 'images/flags/sl.png');
INSERT INTO country (name, code, icon_file) VALUES ('Singapore', 'SG', 'images/flags/sg.png');
INSERT INTO country (name, code, icon_file) VALUES ('Sint Maarten (Dutch part)', 'SX', 'images/flags/sx.png');
INSERT INTO country (name, code, icon_file) VALUES ('Slovakia', 'SK', 'images/flags/sk.png');
INSERT INTO country (name, code, icon_file) VALUES ('Slovenia', 'SI', 'images/flags/si.png');
INSERT INTO country (name, code, icon_file) VALUES ('Solomon Islands', 'SB', 'images/flags/sb.png');
INSERT INTO country (name, code, icon_file) VALUES ('Somalia', 'SO', 'images/flags/so.png');
INSERT INTO country (name, code, icon_file) VALUES ('South Africa', 'ZA', 'images/flags/za.png');
INSERT INTO country (name, code, icon_file) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 'images/flags/gs.png');
INSERT INTO country (name, code, icon_file) VALUES ('South Sudan', 'SS', 'images/flags/ss.png');
INSERT INTO country (name, code, icon_file) VALUES ('Spain', 'ES', 'images/flags/es.png');
INSERT INTO country (name, code, icon_file) VALUES ('Sri Lanka', 'LK', 'images/flags/lk.png');
INSERT INTO country (name, code, icon_file) VALUES ('Sudan', 'SD', 'images/flags/sd.png');
INSERT INTO country (name, code, icon_file) VALUES ('Suriname', 'SR', 'images/flags/sr.png');
INSERT INTO country (name, code, icon_file) VALUES ('Svalbard and Jan Mayen', 'SJ', 'images/flags/sj.png');
INSERT INTO country (name, code, icon_file) VALUES ('Swaziland', 'SZ', 'images/flags/sz.png');
INSERT INTO country (name, code, icon_file) VALUES ('Sweden', 'SE', 'images/flags/se.png');
INSERT INTO country (name, code, icon_file) VALUES ('Switzerland', 'CH', 'images/flags/ch.png');
INSERT INTO country (name, code, icon_file) VALUES ('Syrian Arab Republic', 'SY', 'images/flags/sy.png');
INSERT INTO country (name, code, icon_file) VALUES ('Taiwan, Province of China', 'TW', 'images/flags/tw.png');
INSERT INTO country (name, code, icon_file) VALUES ('Tajikistan', 'TJ', 'images/flags/tj.png');
INSERT INTO country (name, code, icon_file) VALUES ('Tanzania, United Republic of', 'TZ', 'images/flags/tz.png');
INSERT INTO country (name, code, icon_file) VALUES ('Thailand', 'TH', 'images/flags/th.png');
INSERT INTO country (name, code, icon_file) VALUES ('Timor-Leste', 'TL', 'images/flags/tl.png');
INSERT INTO country (name, code, icon_file) VALUES ('Togo', 'TG', 'images/flags/tg.png');
INSERT INTO country (name, code, icon_file) VALUES ('Tokelau', 'TK', 'images/flags/tk.png');
INSERT INTO country (name, code, icon_file) VALUES ('Tonga', 'TO', 'images/flags/to.png');
INSERT INTO country (name, code, icon_file) VALUES ('Trinidad and Tobago', 'TT', 'images/flags/tt.png');
INSERT INTO country (name, code, icon_file) VALUES ('Tunisia', 'TN', 'images/flags/tn.png');
INSERT INTO country (name, code, icon_file) VALUES ('Turkey', 'TR', 'images/flags/tr.png');
INSERT INTO country (name, code, icon_file) VALUES ('Turkmenistan', 'TM', 'images/flags/tm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Turks and Caicos Islands', 'TC', 'images/flags/tc.png');
INSERT INTO country (name, code, icon_file) VALUES ('Tuvalu', 'TV', 'images/flags/tv.png');
INSERT INTO country (name, code, icon_file) VALUES ('Uganda', 'UG', 'images/flags/ug.png');
INSERT INTO country (name, code, icon_file) VALUES ('Ukraine', 'UA', 'images/flags/ua.png');
INSERT INTO country (name, code, icon_file) VALUES ('United Arab Emirates', 'AE', 'images/flags/ae.png');
INSERT INTO country (name, code, icon_file) VALUES ('United Kingdom', 'GB', 'images/flags/gb.png');
INSERT INTO country (name, code, icon_file) VALUES ('United States', 'US', 'images/flags/us.png');
INSERT INTO country (name, code, icon_file) VALUES ('United States Minor Outlying Islands', 'UM', 'images/flags/um.png');
INSERT INTO country (name, code, icon_file) VALUES ('Uruguay', 'UY', 'images/flags/uy.png');
INSERT INTO country (name, code, icon_file) VALUES ('Uzbekistan', 'UZ', 'images/flags/uz.png');
INSERT INTO country (name, code, icon_file) VALUES ('Vanuatu', 'VU', 'images/flags/vu.png');
INSERT INTO country (name, code, icon_file) VALUES ('Venezuela, Bolivarian Republic of', 'VE', 'images/flags/ve.png');
INSERT INTO country (name, code, icon_file) VALUES ('Vietnam', 'VN', 'images/flags/vn.png');
INSERT INTO country (name, code, icon_file) VALUES ('Virgin Islands, British', 'VG', 'images/flags/vg.png');
INSERT INTO country (name, code, icon_file) VALUES ('Virgin Islands, U.S.', 'VI', 'images/flags/vi.png');
INSERT INTO country (name, code, icon_file) VALUES ('Wallis and Futuna', 'WF', 'images/flags/wf.png');
INSERT INTO country (name, code, icon_file) VALUES ('Western Sahara', 'EH', 'images/flags/eh.png');
INSERT INTO country (name, code, icon_file) VALUES ('Yemen', 'YE', 'images/flags/ye.png');
INSERT INTO country (name, code, icon_file) VALUES ('Zambia', 'ZM', 'images/flags/zm.png');
INSERT INTO country (name, code, icon_file) VALUES ('Zimbabwe', 'ZW', 'images/flags/zw.png');