package by.koshko.cyberwikia.bean;

public enum EntityError {
    DUPLICATE_LOGIN,
    DUPLICATE_EMAIL,
    DUPLICATE_NICKNAME,
    DUPLICATE_TEAMNAME,
    USER_HAS_PROFILE,
    REQUIRED_NOT_NULL,
    GENERIC_ERROR,
    PLAYER_NOT_ACTIVE,
    NO_PLAYER_PROFILE
}
